version: '3.8'

services:
  hrms-app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hrms-app
    restart: unless-stopped
    env_file:
      - .env
    ports:
      - "8000:8000"
